const videoList = {
    assassinsCreed: [
        'gfycat:SecretBriskChital',
        'gfycat:RegularCanineGerbil',
        '',
        '',

    ],
    battlefield: [
        'gfycat:AgileMeekIrukandjijellyfish',
        'imgur:3ykvWne',
        'imgur:kMgCYt5',
        'gfycat:AcademicTemptingEnglishpointer',
        'gfycat:JampackedMediumBird',
        '',
        '',
        '',
        '',
        '',
        '',


    ],
    contra3: [
        'imgur:u89VA7b',

    ],
    cuphead: [
        'imgur:6tVdRp3',
    ],
    darkSouls: [
        'imgur:lr1tQRS',
        'gfycat:SandySpryArchaeopteryx',
        'imgur:EQO9X8p',

    ],
    fallout: [
        'imgur:RuWFo6B',
        'gfycat:AmazingRequiredAmericanbobtail',
        'imgur:xYsCgmu',
        'imgur:YJtq0zB',
        '',
        '',
        '',
        '',
        '',
        '',

    ],
    forzaHorizon3: [
        'gfycat:ShinyVigorousCats',

    ],
    ghostReconWildlands: [

        'imgur:A668H16',
        'gfycat:UnawareShadyCrownofthornsstarfish',
        'gfycat:PaleHandyAidi',
        'gfycat:AridFarflungFieldmouse',
        'gfycat:CavernousIdioticAmericancrayfish',
        'imgur:5OaANDn',
        'gfycat:DarlingDangerousChicken',
        'imgur:CdDAc5h',
        'imgur:vPnVIwO',
        'gfycat:InsistentSentimentalBufeo',
        '',
        '',
        '',
        '',

    ],
    grandTheftAuto4: [
        'imgur:k7gQ66O',
    ],
    grandTheftAutoV: [
        'imgur:uNk5woD',
        'gfycat:ForsakenNervousCorydorascatfish',
        'gfycat:FarWhimsicalCivet',
        'imgur:xuxS3DN',
        'gfycat:SimilarOpulentAnemone',
        'gfycat:PepperySentimentalGraywolf',
        'gfycat:SnappyAppropriateAustraliancurlew',
        'imgur:0qnfTk9',
        'gfycat:DirectMassiveHawaiianmonkseal',
        'imgur:YSo4hkD',
        'gfycat:UnknownSparseHoneyeater',
        'gfycat:FancyThinHorse',
        'imgur:4iVHDZk',
        'imgur:eF5Yt8H',
        'gfycat:FrayedGoldenGorilla',
        'imgur:vWhHAgV',
        'gfycat:HarmlessQuestionableAnura',
        'gfycat:EnchantedWindingAegeancat',
        'gfycat:FlawlessThinInexpectatumpleco',
        'imgur:GaBLx9X',
        'imgur:ZOANMrO',
        'gfycat:ConsciousJollyChrysalis',
        'imgur:EOAYAsT',
        'gfycat:TameGrotesqueHarpyeagle',
        'imgur:b7EMEYu',
        'imgur:qmtPDEq',
        'gfycat:DefiniteFearlessCobra',
        'imgur:4XYMSLy',
        'imgur:9xKQTu7',
        'gfycat:PowerfulSecondArcticwolf',
        'imgur:J0s8Ks6',
        'imgur:UNvPoNC',
        'imgur:IOVbtql',
        'imgur:qclx6PM',
        'imgur:K1AuBC5',
        'imgur:oGLtuPr',
        'imgur:ONBKZaj',
        'imgur:dErnnAg',
        'gfycat:ObviousScratchyKingfisher',
        'gfycat:HotDesertedHerring',
        'gfycat:LegitimateSpectacularCygnet',
        'gfycat:CalmUniqueGroundbeetle',
        'gfycat:DarlingScholarlyEkaltadeta',
        'imgur:3dJYKU5',
        'imgur:XEClLfV',
        'imgur:0SxpxDf',
        'gfycat:PartialAliveAquaticleech',
        'gfycat:PinkJauntyCaiman',
        'imgur:PHd4Q0O',
        '',
        '',




    ],
    justCause3: [
        'imgur:trjS6g5',
        'gfycat:CorruptAdmiredIsabellineshrike',
        'gfycat:InnocentColossalCicada',
        'gfycat:BogusHappygoluckyAmurratsnake',
        'gfycat:DelightfulWaryGrebe',
        'gfycat:CheeryNaturalArrowworm',
        'gfycat:SevereContentDarklingbeetle',
        'gfycat:EvilPointedHapuka',
        'gfycat:PerkyPlasticAsp',
        'gfycat:MarvelousFluffyBlobfish',
        'gfycat:TenseInsistentChrysomelid',
        'gfycat:FailingEvergreenKingbird',
        'gfycat:AridBlondBarasingha',
        'imgur:v1ReynT',
        'gfycat:ScratchyJaggedHornet',
        'gfycat:TediousDependentEider',
        'gfycat:CompassionateMiniatureKestrel',
        'imgur:VP8jBPg',
        'gfycat:BewitchedDeliriousGibbon',
        'gfycat:HauntingSafeAntarcticfurseal',
        'gfycat:WarmColorfulJackal',
        'gfycat:HelplessUnevenGlassfrog',
        'gfycat:ThoughtfulFormalAmericanbadger',
        'imgur:TtVzQg2',
        'imgur:47zDmP3',
        'gfycat:CookedGargantuanGangesdolphin',
        'imgur:cWcpEIQ',
        '',
        '',
        '',



    ],
    mario: [

        'imgur:RRKKAdY',
    ],
    overwatch: [
        'gfycat:AridGroundedBactrian',
        'gfycat:BaggyVictoriousIberianmole',
        'gfycat:BeneficialFlippantBelugawhale',
        'gfycat:BossyDistortedBudgie',
        'gfycat:BossyFlippantBlackfly',
        'gfycat:BreakableFairAxolotl',
        'gfycat:CanineScholarlyIbisbill',
        'gfycat:CaringFancyIndianspinyloach',
        'gfycat:CircularExaltedFlounder',
        'gfycat:CoarseSorrowfulCub',
        'gfycat:ConstantBreakableImperialeagle',
        'gfycat:ConstantObedientAfricanjacana',
        'gfycat:CreamyShyCottonmouth',
        'gfycat:DefensiveVillainousHammerkop',
        'gfycat:DeficientSmallEgret',
        'gfycat:DelectableRadiantKiwi',
        'gfycat:DependableGlassBee',
        'gfycat:DigitalOccasionalCygnet',
        'gfycat:EagerGoodGangesdolphin',
        'gfycat:EuphoricKindheartedIbis',
        'gfycat:FavorableRewardingAnura',
        'gfycat:FrankViciousHairstreak',
        'gfycat:FrighteningEmptyArgusfish',
        'gfycat:GeneralVeneratedGermanwirehairedpointer',
        'gfycat:GiftedFrenchAzurevase',
        'gfycat:GlassHappygoluckyArthropods',
        'gfycat:GoldenFreeGonolek',
        'gfycat:IdenticalPaltryAgama',
        'gfycat:ImpartialJitteryDuiker',
        'gfycat:ImpishDimAlbacoretuna',
        'gfycat:ImpressionableLargeIbizanhound',
        'gfycat:InfantileAdmiredDromedary',
        'gfycat:InfiniteImmediateIberianlynx',
        'gfycat:InstructiveMeanGuanaco',
        'gfycat:JampackedFreshHoopoe',
        'gfycat:LastingVacantBlackfish',
        'gfycat:LightDarkDrongo',
        'gfycat:LightheartedSmallEastrussiancoursinghounds',
        'gfycat:LonelyUntriedBluefish',
        'gfycat:MellowAnyHochstettersfrog',
        'gfycat:MellowBlackHoneybee',
        'gfycat:MerryNeglectedKinglet',
        'gfycat:MisguidedGlaringGrassspider',
        'gfycat:NaiveHopefulBergerpicard',
        'gfycat:NaturalWhisperedAfricanjacana',
        'gfycat:NecessaryGoldenDevilfish',
        'gfycat:NecessaryWastefulGuineafowl',
        'gfycat:OblongBewitchedBelugawhale',
        'gfycat:OldSpryFennecfox',
        'gfycat:OrneryIcyArcticwolf',
        'gfycat:PassionateGrandioseKinglet',
        'gfycat:PlainSecretGraysquirrel',
        'gfycat:PlumpIdioticKoalabear',
        'gfycat:PresentDisgustingAplomadofalcon',
        'gfycat:QuickImpartialKob',
        'gfycat:RedThirstyHeterodontosaurus',
        'gfycat:SaltyAggressiveCockerspaniel',
        'gfycat:SatisfiedSpiffyJaguar',
        'gfycat:ScrawnyDrearyDaddylonglegs',
        'gfycat:ShabbyAltruisticCreature',
        'gfycat:SleepyBreakableFrog',
        'gfycat:SmoggyQueasyFish',
        'gfycat:TestyWhichBuzzard',
        'gfycat:ThinColorfulAmericancrayfish',
        'gfycat:UnawareSorrowfulIndianglassfish',
        'gfycat:UnderstatedFearlessCoati',
        'gfycat:UnlinedEnchantingAsiansmallclawedotter',
        'gfycat:UnrealisticSilverFlamingo',
        'gfycat:UnripeVelvetyAmethystsunbird',
        'gfycat:UnsteadyCloseHedgehog',
        'gfycat:VerifiableTeemingAnemonecrab',
        'gfycat:WatchfulFreeCock',
        'gfycat:WeepyHonorableEasternnewt',
        'gfycat:WeightyLikableBrant',
        'gfycat:WeightyRealisticDwarfmongoose',
        'gfycat:WellwornTatteredEyra',
        'gfycat:ZigzagJealousIrishredandwhitesetter',
        'imgur:nHqy2FF',
        'imgur:Gw63577',
        'imgur:XRUjTjv',
        'imgur:oegdyME',
        'imgur:KXXcGMJ',
        'imgur:tLIzoE1',
        'imgur:6chBdw5',
        'imgur:To2UDdM',
        'imgur:GwnF00r',
        'gfycat:EquatorialAdeptHammerheadshark',
        'imgur:uy4C4I1',
        'gfycat:PoliteZanyGrouper',
        'imgur:WOutVGu',
        'gfycat:BackPoshHawaiianmonkseal',
        'gfycat:HandsomeUnimportantAngelfish',
        'gfycat:FaintGregariousKoala',
        'gfycat:TerribleFineHammerheadshark',

        'gfycat:InferiorPeskyAustraliankelpie',
        'gfycat:WhirlwindLonelyDachshund',
        'gfycat:GracefulUnconsciousAustraliankelpie',
        'gfycat:FluidIdenticalAmericanquarterhorse',
        'gfycat:MajorBlackandwhiteColt',
    ],
    other: [
        'imgur:P8MhFTn',
        'imgur:ICvySRr',
        'imgur:HNfYrDk',
        'imgur:ZbPU4D4',
        'imgur:pWKPmx7',
        'gfycat:DearFlawedAmericancreamdraft',
        'gfycat:AffectionateLeafyGermanwirehairedpointer',
        'imgur:Q8z3Wr9',
    ],
    playerUnknownsBattleground: [
        'gfycat:LameWeeBluebreastedkookaburra'
    ],
    portal: [
        'imgur:b3kjvHm',
    ],
    rocketLeague: [
        'gfycat:ElderlyThreadbareHuemul',
        'imgur:IRhpB15',
        'gfycat:ConfusedElderlyBorzoi',
        'gfycat:ShadyImprobableIberianbarbel',
        'gfycat:GreedyLimitedBalloonfish',
        'gfycat:DenseSarcasticDogwoodtwigborer',
        'gfycat:LankyEsteemedBoar',
        '',
        '',
        '',
        '',

    ],
    teamFortress2: [
        'gfycat:ImperturbableTintedHorse'
    ],
    witcher3: [
        'gfycat:LeanFlawedIberianchiffchaff',
        'imgur:nnQsyej',
    ],
    worldOfWarcraft: [

        'imgur:agZISAX',

        'imgur:JAZClBI',
    ],









}

module.exports = videoList;