const videoList = {
    overwatch: [
        'gfycat:AridGroundedBactrian',
        'gfycat:BaggyVictoriousIberianmole',
        'gfycat:BeneficialFlippantBelugawhale',
        'gfycat:BossyDistortedBudgie',
        'gfycat:BossyFlippantBlackfly',
        'gfycat:BreakableFairAxolotl',
        'gfycat:CanineScholarlyIbisbill',
        'gfycat:CaringFancyIndianspinyloach',
        'gfycat:CircularExaltedFlounder',
        'gfycat:CoarseSorrowfulCub',
        'gfycat:ConstantBreakableImperialeagle',
        'gfycat:ConstantObedientAfricanjacana',
        'gfycat:CreamyShyCottonmouth',
        'gfycat:DefensiveVillainousHammerkop',
        'gfycat:DeficientSmallEgret',
        'gfycat:DelectableRadiantKiwi',
        'gfycat:DependableGlassBee',
        'gfycat:DigitalOccasionalCygnet',
        'gfycat:EagerGoodGangesdolphin',
        'gfycat:EuphoricKindheartedIbis',
        'gfycat:FavorableRewardingAnura',
        'gfycat:FrankViciousHairstreak',
        'gfycat:FrighteningEmptyArgusfish',
        'gfycat:GeneralVeneratedGermanwirehairedpointer',
        'gfycat:GiftedFrenchAzurevase',
        'gfycat:GlassHappygoluckyArthropods',
        'gfycat:GoldenFreeGonolek',
        'gfycat:IdenticalPaltryAgama',
        'gfycat:ImpartialJitteryDuiker',
        'gfycat:ImpishDimAlbacoretuna',
        'gfycat:ImpressionableLargeIbizanhound',
        'gfycat:InfantileAdmiredDromedary',
        'gfycat:InfiniteImmediateIberianlynx',
        'gfycat:InstructiveMeanGuanaco',
        'gfycat:JampackedFreshHoopoe',
        'gfycat:LastingVacantBlackfish',
        'gfycat:LightDarkDrongo',
        'gfycat:LightheartedSmallEastrussiancoursinghounds',
        'gfycat:LonelyUntriedBluefish',
        'gfycat:MellowAnyHochstettersfrog',
        'gfycat:MellowBlackHoneybee',
        'gfycat:MerryNeglectedKinglet',
        'gfycat:MisguidedGlaringGrassspider',
        'gfycat:NaiveHopefulBergerpicard',
        'gfycat:NaturalWhisperedAfricanjacana',
        'gfycat:NecessaryGoldenDevilfish',
        'gfycat:NecessaryWastefulGuineafowl',
        'gfycat:OblongBewitchedBelugawhale',
        'gfycat:OldSpryFennecfox',
        'gfycat:OrneryIcyArcticwolf',
        'gfycat:PassionateGrandioseKinglet',
        'gfycat:PlainSecretGraysquirrel',
        'gfycat:PlumpIdioticKoalabear',
        'gfycat:PresentDisgustingAplomadofalcon',
        'gfycat:QuickImpartialKob',
        'gfycat:RedThirstyHeterodontosaurus',
        'gfycat:SaltyAggressiveCockerspaniel',
        'gfycat:SatisfiedSpiffyJaguar',
        'gfycat:ScrawnyDrearyDaddylonglegs',
        'gfycat:ShabbyAltruisticCreature',
        'gfycat:SleepyBreakableFrog',
        'gfycat:SmoggyQueasyFish',
        'gfycat:TestyWhichBuzzard',
        'gfycat:ThinColorfulAmericancrayfish',
        'gfycat:UnawareSorrowfulIndianglassfish',
        'gfycat:UnderstatedFearlessCoati',
        'gfycat:UnlinedEnchantingAsiansmallclawedotter',
        'gfycat:UnrealisticSilverFlamingo',
        'gfycat:UnripeVelvetyAmethystsunbird',
        'gfycat:UnsteadyCloseHedgehog',
        'gfycat:VerifiableTeemingAnemonecrab',
        'gfycat:WatchfulFreeCock',
        'gfycat:WeepyHonorableEasternnewt',
        'gfycat:WeightyLikableBrant',
        'gfycat:WeightyRealisticDwarfmongoose',
        'gfycat:WellwornTatteredEyra',
        'gfycat:ZigzagJealousIrishredandwhitesetter',
        'imgur:nHqy2FF',
        'imgur:Gw63577',
        'imgur:XRUjTjv',
        'imgur:oegdyME',
        'imgur:KXXcGMJ',
        'imgur:tLIzoE1',
        'imgur:6chBdw5',
        'imgur:To2UDdM',
        'imgur:GwnF00r',
        'gfycat:EquatorialAdeptHammerheadshark',
        'imgur:uy4C4I1',
        'gfycat:PoliteZanyGrouper',
        'imgur:WOutVGu',
        'gfycat:BackPoshHawaiianmonkseal',
        'gfycat:HandsomeUnimportantAngelfish',
        'gfycat:FaintGregariousKoala',
        'gfycat:TerribleFineHammerheadshark',

        'gfycat:InferiorPeskyAustraliankelpie',
        'gfycat:WhirlwindLonelyDachshund',
        'gfycat:GracefulUnconsciousAustraliankelpie',
        'gfycat:FluidIdenticalAmericanquarterhorse',
        'gfycat:MajorBlackandwhiteColt',
    ],
    grandTheftAutoV: [
        'imgur:uNk5woD',
        'gfycat:ForsakenNervousCorydorascatfish',
        'gfycat:FarWhimsicalCivet',
        'imgur:xuxS3DN',
        'gfycat:SimilarOpulentAnemone',
        'gfycat:PepperySentimentalGraywolf',
        'gfycat:SnappyAppropriateAustraliancurlew',
        'imgur:0qnfTk9',
    ],
    rocketLeague: [
        'gfycat:ElderlyThreadbareHuemul',
        'imgur:IRhpB15',
        'gfycat:ConfusedElderlyBorzoi',
        'gfycat:ShadyImprobableIberianbarbel',
        'gfycat:GreedyLimitedBalloonfish',

    ],
    justCause: [

        'imgur:trjS6g5',
    ],
    battlefield: [
        'gfycat:AgileMeekIrukandjijellyfish',

        'imgur:kMgCYt5',
    ],
    forzaHorizon3: [
        'gfycat:ShinyVigorousCats',

    ],
    ghostReconWildlands: [

        'imgur:A668H16',
    ],
    worldOfWarcraft: [

        'imgur:agZISAX',

        'imgur:JAZClBI',
    ],
    mario: [

        'imgur:RRKKAdY',
    ],
    playerUnknownsBattleground: [
        'gfycat:LameWeeBluebreastedkookaburra'
    ],
    darkSouls: [
        'imgur:lr1tQRS',
    ],
    witcher3: [
        'gfycat:LeanFlawedIberianchiffchaff',
    ],
    other: [
        'imgur:P8MhFTn',
        'imgur:ICvySRr',
        'imgur:HNfYrDk',
        'imgur:ZbPU4D4',
        'imgur:TuISmiO',
        'imgur:pWKPmx7',
        'gfycat:DearFlawedAmericancreamdraft',
        'gfycat:AffectionateLeafyGermanwirehairedpointer',
        'imgur:b3kjvHm',
    ]

}

module.exports = videoList;